### PR TITLE
Builder: Electra

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

implements https://github.com/ethereum/builder-specs/pull/101

**does not include** 
- https://github.com/ethereum/builder-specs/pull/104
- E2E enabled testing for Electra

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

### CODE REVIEW

File: go.mod [hunk 1]
```diff
@@ -284,3 +284,5 @@ replace github.com/json-iterator/go => github.com/prestonvanloon/go v1.1.7-0.201
 
 // See https://github.com/prysmaticlabs/grpc-gateway/issues/2
 replace github.com/grpc-ecosystem/grpc-gateway/v2 => github.com/prysmaticlabs/grpc-gateway/v2 v2.3.1-0.20230315201114-09284ba20446
+
+replace github.com/ethereum/go-ethereum => github.com/lightclient/go-ethereum v1.10.10-0.20240726203109-4a0622f95d30
```
Comment (james-prysm) [inline go.mod:288]: temp uses lightclient's fork to use the updated libraries in e2e

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 2]
```diff
@@ -270,13 +281,17 @@ func (vs *Server) getPayloadHeaderFromBuilder(ctx context.Context, slot primitiv
...
-			return nil, fmt.Errorf("builder returned too many kzg commitments: %d", len(kzgCommitments))
+	}
+
+	var executionRequests *enginev1.ExecutionRequests
+	if bid.Version() >= version.Electra {
+		eBid, ok := bid.(builder.BidElectra)
+		if !ok {
+			return nil, errors.New("builder returned non-electra bid")
 		}
-		for _, c := range kzgCommitments {
```
Comment (james-prysm) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:276]: removing this validation as we already validate when we convert the bid from json to proto

File: testing/middleware/builder/builder.go [hunk 3]
```diff
@@ -334,6 +345,11 @@ func (p *Builder) handleHeaderRequest(w http.ResponseWriter, req *http.Request)
 	}
 	ax := types.Slot(slot)
 	currEpoch := types.Epoch(ax / params.BeaconConfig().SlotsPerEpoch)
+	//if currEpoch >= params.BeaconConfig().ElectraForkEpoch {
```
Comment (james-prysm) [inline testing/middleware/builder/builder.go:348]: electra isn't supported yet

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 4]
```diff
@@ -270,23 +281,17 @@ func (vs *Server) getPayloadHeaderFromBuilder(
...
-	var kzgCommitments [][]byte
-	if bid.Version() >= version.Deneb {
-		kzgCommitments, err = bid.BlobKzgCommitments()
-		if err != nil {
-			return nil, errors.Wrap(err, "could not get blob kzg commitments")
+	var executionRequests *enginev1.ExecutionRequests
+	if bid.Version() >= version.Electra {
+		eBid, ok := bid.(builder.BidElectra)
+		if !ok {
+			return nil, errors.New("builder returned non-electra bid")
```
Comment (rkapka) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:288]: Related to my comment above about `if ok` - here you do return an error, so let's pick one approach and be consistent about this

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 5]
```diff
@@ -295,8 +300,10 @@ func (vs *Server) getPayloadHeaderFromBuilder(
 		"validator":          idx,
 		"sinceSlotStartTime": time.Since(t),
 	})
-	if len(kzgCommitments) > 0 {
-		l = l.WithField("kzgCommitmentCount", len(kzgCommitments))
```
Comment (rkapka) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:299]: This should not be removed

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 6]
```diff
@@ -407,6 +413,14 @@ func setExecution(blk interfaces.SignedBeaconBlock, execution interfaces.Executi
 		return errors.Wrap(err, errMessage)
 	}
 
+	// If the block version is below Electra, no further actions are needed
+	if blk.Version() < version.Electra {
+		return nil
+	}
+
+	if err := blk.SetExecutionRequests(requests); err != nil {
+		return errors.Wrap(err, errMessage)
```
Comment (rkapka) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:422]: You have to update `errMessage` because it currently describes KZG commitments. But honestly I feel that it only makes sense to use `errMessage` for `SetExecution` because it removes duplication. It doesn't help to update it later only to use it in one place (in fact, it can lead to bugs such as this one).

File: changelog/james-prysm_builder-electra.md [hunk 7]
```diff
@@ -0,0 +1,3 @@
+### Added
+
+- Builder API endpooint to support Electra
```
Comment (rkapka) [inline changelog/james-prysm_builder-electra.md:3]:
```suggestion
- Builder API endpoint to support Electra
```

File: testing/middleware/builder/builder.go [hunk 8]
```diff
@@ -56,6 +57,8 @@ const (
 	GetPayloadMethodV2 = "engine_getPayloadV2"
 	// GetPayloadMethodV3 v3 request string for JSON-RPC.
 	GetPayloadMethodV3 = "engine_getPayloadV3"
+	// GetPayloadMethodV4 v3 request string for JSON-RPC.
```
Comment (rkapka) [inline testing/middleware/builder/builder.go:60]:
```suggestion
	// GetPayloadMethodV4 v4 request string for JSON-RPC.
```
Actually, can't it be just `GetPayloadMethodV4 request string for JSON-RPC`? Similarly for other versions

File: testing/middleware/builder/builder.go (hunk 3 above)
Comment (rkapka) [reply testing/middleware/builder/builder.go:348]: OK, but we can comment only this `if` and the rest can be uncommented

File: testing/middleware/builder/builder.go [hunk 9]
```diff
@@ -581,6 +597,92 @@ func (p *Builder) handleHeaderRequestDeneb(w http.ResponseWriter) {
 	w.WriteHeader(http.StatusOK)
 }
 
+//func (p *Builder) handleHeaderRequestElectra(w http.ResponseWriter) {
```
Comment (rkapka) [inline testing/middleware/builder/builder.go:600]: You don't handle execution requests here

File: testing/middleware/builder/builder.go [hunk 10]
```diff
@@ -775,6 +953,23 @@ func executableDataToBlock(params engine.ExecutableData, prevBeaconRoot []byte)
...
+	//if params.WithdrawalRequests != nil {
+	//	for _, req := range params.WithdrawalRequests {
+	//		requests = append(requests, gethTypes.NewRequest(req))
+	//	}
+	//}
+	//if params.ConsolidationRequests != nil {
+	//	for _, req := range params.ConsolidationRequests {
+	//		requests = append(requests, gethTypes.NewRequest(req))
+	//	}
+	//}
```
Comment (rkapka) [inline testing/middleware/builder/builder.go:972]: This doesn't have to commented, I think?

File: testing/middleware/builder/builder.go [hunk 11]
```diff
@@ -611,6 +713,52 @@ func (p *Builder) handleBlindedBlock(w http.ResponseWriter, req *http.Request) {
...
+// ExecutionPayloadResponseFromData converts an ExecutionData interface value to a payload response.
+// This involves serializing the execution payload value so that the abstract payload envelope can be used.
+func ExecutionPayloadResponseFromData(ed interfaces.ExecutionData, bundle *v1.BlobsBundle) (*builderAPI.ExecutionPayloadResponse, error) {
+	pb := ed.Proto()
+	var data interface{}
+	var err error
+	var ver string
+	switch pbStruct := pb.(type) {
+	case *v1.ExecutionPayloadDeneb:
+		// TODO: add ELECTRA here
```
Comment (rkapka) [inline testing/middleware/builder/builder.go:727]: I don't thing there's anything blocking you from adding Electra here?

File: testing/middleware/builder/builder.go [hunk 12]
```diff
@@ -690,6 +838,36 @@ func (p *Builder) retrievePendingBlockDeneb() (*v1.ExecutionPayloadDenebWithValu
 	return denebPayload, nil
 }
 
+//func (p *Builder) retrievePendingBlockElectra() (*v1.ExecutionPayloadElectraWithValueAndBlobsBundle, error) {
```
Comment (rkapka) [inline testing/middleware/builder/builder.go:841]: I think this doesn't have to be commented and you can resolve the TODO inside this function in this PR.

File: api/client/builder/types.go [hunk 13]
```diff
@@ -1307,6 +1269,210 @@ func (p *ExecutionPayloadDeneb) ToProto() (*v1.ExecutionPayloadDeneb, error) {
...
+	}
+	kzgCommitments := make([][]byte, len(bb.BlobKzgCommitments))
+	for i, commit := range bb.BlobKzgCommitments {
+		if len(commit) != fieldparams.BLSPubkeyLength {
+			return nil, fmt.Errorf("commitment length %d is not %d", len(commit), fieldparams.BLSPubkeyLength)
+		}
+		kzgCommitments[i] = bytesutil.SafeCopyBytes(commit)
+	}
+	if bb.ExecutionRequests == nil {
+		return nil, fmt.Errorf("execution requests is empty")
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply api/client/builder/types.go:1309]: we shouldn't be, will fix

File: beacon-chain/builder/testing/mock.go [hunk 14]
```diff
@@ -65,13 +66,22 @@ func (s *MockBuilderService) SubmitBlindedBlock(_ context.Context, b interfaces.
 			return nil, nil, errors.Wrap(err, "could not wrap deneb payload")
 		}
 		return w, s.BlobBundle, s.ErrSubmitBlindedBlock
+	case version.Electra:
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply beacon-chain/builder/testing/mock.go:69]: yes we should merge this

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 15]
```diff
@@ -72,20 +72,31 @@ func setExecutionData(ctx context.Context, blk interfaces.SignedBeaconBlock, loc
...
+	var executionRequests *enginev1.ExecutionRequests
+	if bid.Version() >= version.Electra {
+		bidElectra, ok := bid.(builder.BidElectra)
+		if ok {
+			executionRequests, err = bidElectra.ExecutionRequests()
+			if err != nil {
+				log.WithError(err).Warn("Proposer: failed to retrieve execution requests from BuilderBid")
+			}
+		}
+	}
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:98]: it's because the kzgCommitments were there i can move both

File: api/client/builder/bid.go [hunk 16]
```diff
@@ -290,3 +297,101 @@ func (b signedBuilderBidDeneb) Version() int {
...
+
+// ExecutionRequests --
+func (b builderBidElectra) ExecutionRequests() (*v1.ExecutionRequests, error) {
+	if b.p == nil {
+		return nil, consensus_types.ErrNilObjectWrapped
+	}
+	if b.p.ExecutionRequests == nil {
+		return nil, errors.New("ExecutionRequests is nil")
+	}
+	return b.p.ExecutionRequests, nil
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply api/client/builder/bid.go:358]: is this just adding a comment saying we aren't copying ?

File: api/client/builder/bid.go [hunk 17]
```diff
@@ -290,3 +297,101 @@ func (b signedBuilderBidDeneb) Version() int {
...
+}
+
+// ExecutionRequests --
+func (b builderBidElectra) ExecutionRequests() (*v1.ExecutionRequests, error) {
+	if b.p == nil {
+		return nil, consensus_types.ErrNilObjectWrapped
+	}
+	if b.p.ExecutionRequests == nil {
+		return nil, errors.New("ExecutionRequests is nil")
+	}
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply api/client/builder/bid.go:357]: ok i guess i can remove it and keep it similar to blob kzg commitments

[the remark this answers is not in the document]
Comment (james-prysm) [reply api/client/builder/bid.go:357]: let me see if i can just remove it

File: testing/middleware/builder/builder.go (hunk 9 above)
Comment (james-prysm) [reply testing/middleware/builder/builder.go]: I added it

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go [hunk 18]
```diff
@@ -326,11 +315,6 @@ func TestServer_setExecutionData(t *testing.T) {
 		require.NoError(t, err)
 		_, err = builderBid.Header()
 		require.NoError(t, err)
-		builderKzgCommitments, err := builderBid.BlobKzgCommitments()
```
Comment (james-prysm) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go:329]: we don't need this for capella tests

File: consensus-types/blocks/setters.go [hunk 19]
```diff
@@ -179,6 +180,9 @@ func (b *SignedBeaconBlock) SetExecutionRequests(req *enginev1.ExecutionRequests
 	if b.version < version.Electra {
 		return consensus_types.ErrNotSupported("SetExecutionRequests", b.version)
 	}
+	if req == nil {
+		return errors.New("nil execution request")
```
Comment (james-prysm) [inline consensus-types/blocks/setters.go:184]: should I throw an error or just set it to an empty request object?

File: testing/middleware/builder/builder.go [hunk 20]
```diff
@@ -576,12 +595,148 @@ func (p *Builder) handleHeaderRequestDeneb(w http.ResponseWriter) {
...
+		},
+	}
+
+	err = json.NewEncoder(w).Encode(hdrResp)
+	if err != nil {
+		p.cfg.logger.WithError(err).Error("Could not encode response")
+		http.Error(w, err.Error(), http.StatusInternalServerError)
+		return
+	}
+	p.currVersion = version.Electra
```
Comment (james-prysm) [inline testing/middleware/builder/builder.go:732]: i'm not sure if this is the best way to do it, it's because the payload is still deneb so I can't do it by payload version

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go (hunk 6 above)
Comment (james-prysm) [reply beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:431]: just adding my own custom error here

File: api/client/builder/client_test.go [hunk 21]
```diff
@@ -292,6 +292,50 @@ func TestClient_GetHeader(t *testing.T) {
 		_, err := c.GetHeader(ctx, slot, bytesutil.ToBytes32(parentHash), bytesutil.ToBytes48(pubkey))
 		require.ErrorContains(t, "could not extract proto message from header: too many blob commitments: 7", err)
 	})
+	t.Run("electra", func(t *testing.T) {
```
Comment (james-prysm) [inline api/client/builder/client_test.go:295]: should i add any more kinds of tests?

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 22]
```diff
@@ -72,17 +72,29 @@ func setExecutionData(ctx context.Context, blk interfaces.SignedBeaconBlock, loc
...
+
+	var executionRequests *enginev1.ExecutionRequests
+	if bid.Version() >= version.Electra {
+		bidElectra, ok := bid.(builder.BidElectra)
+		if !ok {
+			log.Warnf("bid type %T does not implement builder.BidElectra ", bid)
+		} else {
+			executionRequests = bidElectra.ExecutionRequests()
```
Comment (terencechain) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:97]: we dont need to do this until after: `higherValueBuilder && withdrawalsMatched`
for the default bellatrix case, we can just set them as nil: `setBuilderExecution(blk, builderPayload, nil, nil)`

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 23]
```diff
@@ -399,14 +414,27 @@ func setExecution(blk interfaces.SignedBeaconBlock, execution interfaces.Executi
...
+	if blk.Version() < version.Electra {
+		return nil
+	}
+
+	// Set the execution requests
+	requestsErr := "failed to set local execution requests"
+	if isBlinded {
+		requestsErr = "failed to set builder execution requests"
+	}
+	if err := blk.SetExecutionRequests(requests); err != nil {
```
Comment (terencechain) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:435]: If a builder returns us an invalid execution requests, shouldn't we default to local block?

File: api/client/builder/types.go [hunk 24]
```diff
@@ -1307,6 +1275,208 @@ func (p *ExecutionPayloadDeneb) ToProto() (*v1.ExecutionPayloadDeneb, error) {
 	}, nil
 }
 
+// ExecHeaderResponseElectra is the header response for builder API /eth/v1/builder/header/{slot}/{parent_hash}/{pubkey}.
+type ExecHeaderResponseElectra struct {
```
Comment (terencechain) [inline api/client/builder/types.go:1279]: Why cant the testing middleware uses this struct here? 
https://github.com/prysmaticlabs/prysm/blob/5bbbad65bc2287c50a8a17e4dd8410ad5ea75427/testing/middleware/builder/builder.go#L109

File: api/client/builder/types.go [hunk 25]
```diff
@@ -1307,6 +1275,208 @@ func (p *ExecutionPayloadDeneb) ToProto() (*v1.ExecutionPayloadDeneb, error) {
...
+	for i, commit := range bb.BlobKzgCommitments {
+		if len(commit) != fieldparams.BLSPubkeyLength {
+			return nil, fmt.Errorf("commitment length %d is not %d", len(commit), fieldparams.BLSPubkeyLength)
+		}
+		kzgCommitments[i] = bytesutil.SafeCopyBytes(commit)
+	}
+	if bb.ExecutionRequests == nil {
+		return nil, errors.New("execution requests is empty")
+	}
+	ExecutionRequests, err := bb.ExecutionRequests.ToProto()
```
Comment (terencechain) [inline api/client/builder/types.go:1317]: Why is `ExecutionRequests` cap?

File: config/params/config.go [hunk 26]
```diff
@@ -395,6 +395,14 @@ func (b *BeaconChainConfig) MaxBlobsPerBlock(slot primitives.Slot) int {
 	return b.DeprecatedMaxBlobsPerBlock
 }
 
+// MaxBlobsPerBlockByVersion returns the maximum number of blobs per block for the given fork version
+func (b *BeaconChainConfig) MaxBlobsPerBlockByVersion(v int) int {
```
Comment (terencechain) [inline config/params/config.go:399]: Please add a test for this helper function

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go (hunk 23 above)
Comment (james-prysm) [reply beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:435]: isn't that what we do? it returns an error and then it falls back to 
```
	if err := setBuilderExecution(blk, builderPayload, builderKzgCommitments, executionRequests); err != nil {
				log.WithError(err).Warn("Proposer: failed to set builder payload")
				return local.Bid, local.BlobsBundle, setLocalExecution(blk, local)
```

File: api/client/builder/types.go (hunk 24 above)
Comment (james-prysm) [reply api/client/builder/types.go:1279]: good question i'm not sure i should fix the old ones too

File: api/client/builder/types.go [hunk 27]
```diff
@@ -605,17 +563,28 @@ type BlobBundler interface {
...
-	case version.String(version.Deneb):
+	}
+	if v >= version.Deneb {
 		toProto = &ExecutionPayloadDenebAndBlobsBundle{}
-	default:
-		return nil, consensusblocks.ErrUnsupportedVersion
+	}
+	if toProto == nil {
+		return nil, fmt.Errorf("unsupported version %s", strings.ToLower(r.Version))
 	}
```
Comment (rkapka) [inline api/client/builder/types.go:588]: Doing it this way, you'll assign to `toProto` 3 times if the version is Deneb or later. Using `else` and reverting the order fixes it.
```
if v >= version.Deneb {
    toProto = &ExecutionPayloadDenebAndBlobsBundle{}
} else if v >= version.Capella {
    toProto = &ExecutionPayloadCapella{}
} else if v >= version.Bellatrix {
    toProto = &ExecutionPayload{}
} else {
    return nil, fmt.Errorf("unsupported version %s", strings.ToLower(r.Version))
}

File: api/client/builder/types.go [hunk 28]
```diff
@@ -1307,6 +1277,209 @@ func (p *ExecutionPayloadDeneb) ToProto() (*v1.ExecutionPayloadDeneb, error) {
...
+	deposits := make([]*v1.DepositRequest, len(er.Deposits))
+	for i, dep := range er.Deposits {
+		d, err := dep.ToProto()
+		if err != nil {
+			return nil, err
+		}
+		deposits[i] = d
+	}
+	if uint64(len(er.Withdrawals)) > params.BeaconConfig().MaxWithdrawalRequestsPerPayload {
+		return nil, fmt.Errorf("withdrawal requests %d exceeds the maximum %d", len(er.Withdrawals), params.BeaconConfig().MaxWithdrawalRequestsPerPayload)
```
Comment (rkapka) [inline api/client/builder/types.go:1355]:
```suggestion
		return nil, fmt.Errorf("withdrawal requests count %d exceeds the maximum %d", len(er.Withdrawals), params.BeaconConfig().MaxWithdrawalRequestsPerPayload)
```

File: api/client/builder/types.go [hunk 29]
```diff
@@ -1307,6 +1277,209 @@ func (p *ExecutionPayloadDeneb) ToProto() (*v1.ExecutionPayloadDeneb, error) {
...
+	withdrawals := make([]*v1.WithdrawalRequest, len(er.Withdrawals))
+	for i, wr := range er.Withdrawals {
+		w, err := wr.ToProto()
+		if err != nil {
+			return nil, err
+		}
+		withdrawals[i] = w
+	}
+	if uint64(len(er.Consolidations)) > params.BeaconConfig().MaxConsolidationsRequestsPerPayload {
+		return nil, fmt.Errorf("consolidation requests %d exceeds the maximum %d", len(er.Consolidations), params.BeaconConfig().MaxConsolidationsRequestsPerPayload)
```
Comment (rkapka) [inline api/client/builder/types.go:1366]:
```suggestion
		return nil, fmt.Errorf("consolidation requests count %d exceeds the maximum %d", len(er.Consolidations), params.BeaconConfig().MaxConsolidationsRequestsPerPayload)
```

File: api/client/builder/types.go [hunk 30]
```diff
@@ -1307,6 +1277,209 @@ func (p *ExecutionPayloadDeneb) ToProto() (*v1.ExecutionPayloadDeneb, error) {
...
+// BuilderBidElectra is a field of ExecHeaderResponseElectra.
+type BuilderBidElectra struct {
+	Header             *ExecutionPayloadHeaderDeneb `json:"header"`
+	BlobKzgCommitments []hexutil.Bytes              `json:"blob_kzg_commitments"`
+	ExecutionRequests  *ExecutionRequestsV1         `json:"execution_requests"`
+	Value              Uint256                      `json:"value"`
+	Pubkey             hexutil.Bytes                `json:"pubkey"`
+}
+
+type ExecutionPayloadHeaderElectra = ExecutionPayloadHeaderDeneb
```
Comment (rkapka) [inline api/client/builder/types.go:1392]: You removed `ExecutionPayloadElectra` but not this type (see comment https://github.com/prysmaticlabs/prysm/pull/14344#discussion_r1918953189)

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 31]
```diff
@@ -136,7 +128,26 @@ func setExecutionData(ctx context.Context, blk interfaces.SignedBeaconBlock, loc
...
+				} else {
+					builderKzgCommitments = bidDeneb.BlobKzgCommitments()
+				}
+			}
+
+			var executionRequests *enginev1.ExecutionRequests
+			if bid.Version() >= version.Electra {
+				bidElectra, ok := bid.(builder.BidElectra)
+				if !ok {
+					log.Warnf("bid type %T does not implement builder.BidElectra ", bid)
```
Comment (rkapka) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:145]:
```suggestion
					log.Warnf("bid type %T does not implement builder.BidElectra", bid)
```

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 32]
```diff
@@ -136,7 +128,26 @@ func setExecutionData(ctx context.Context, blk interfaces.SignedBeaconBlock, loc
 
 		// If we can't get the builder value, just use local block.
 		if higherValueBuilder && withdrawalsMatched { // Builder value is higher and withdrawals match.
-			if err := setBuilderExecution(blk, builderPayload, builderKzgCommitments); err != nil {
+			var builderKzgCommitments [][]byte
+			if bid.Version() >= version.Deneb {
+				bidDeneb, ok := bid.(builder.BidDeneb)
+				if !ok {
+					log.Warnf("bid type %T does not implement builder.BidDeneb ", bid)
```
Comment (rkapka) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:135]:
```suggestion
					log.Warnf("bid type %T does not implement builder.BidDeneb", bid)
```

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 33]
```diff
@@ -270,23 +281,22 @@ func (vs *Server) getPayloadHeaderFromBuilder(
...
 
-	maxBlobsPerBlock := params.BeaconConfig().MaxBlobsPerBlock(slot)
 	var kzgCommitments [][]byte
 	if bid.Version() >= version.Deneb {
-		kzgCommitments, err = bid.BlobKzgCommitments()
-		if err != nil {
-			return nil, errors.Wrap(err, "could not get blob kzg commitments")
+		dBid, ok := bid.(builder.BidDeneb)
+		if !ok {
+			return nil, errors.New("builder returned non-deneb or above bid")
```
Comment (rkapka) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:288]:
```suggestion
			return fmt.Errorf("bid type %T does not implement builder.BidDeneb", dBid)
```
For unity with above warning logs

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go [hunk 34]
```diff
@@ -270,23 +281,22 @@ func (vs *Server) getPayloadHeaderFromBuilder(
...
-			if len(c) != fieldparams.BLSPubkeyLength {
-				return nil, fmt.Errorf("builder returned invalid kzg commitment length: %d", len(c))
-			}
+		kzgCommitments = dBid.BlobKzgCommitments()
+	}
+	var executionRequests *enginev1.ExecutionRequests
+	if bid.Version() >= version.Electra {
+		eBid, ok := bid.(builder.BidElectra)
+		if !ok {
+			return nil, errors.New("builder returned non-electra or above bid")
```
Comment (rkapka) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:296]:
```suggestion
			return fmt.Errorf("bid type %T does not implement builder.BidElectra", eBid)
```
For unity with above warning logs

File: consensus-types/blocks/setters.go (hunk 19 above)
Comment (rkapka) [reply consensus-types/blocks/setters.go:184]: In my opinion it's bad practice to have different ways of handling the same thing within one package. We don't check this in other setters, so we should just skip it here too.

**Review by rkapka — APPROVED** [review]
