### ISSUE TITLE
Startup script doesn't work on MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by mangoleap** [prysmaticlabs/prysm#5590]
That's the output:

> → ./prysm.sh beacon-chain
> Latest Prysm version is v1.0.0-alpha.5.
> Beacon chain is up to date.
> Validator is up to date.
> Starting Prysm beacon-chain 
> dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
>   Referenced from: /Users/mini/prysm/./dist/beacon-chain-v1.0.0-alpha.5-darwin-amd64
>   Expected in: flat namespace
> 
> dyld: Symbol not found: ____chkstk_darwin
>   Referenced from: /Users/mini/prysm/./dist/beacon-chain-v1.0.0-alpha.5-darwin-amd64
>   Expected in: flat namespace
> 
> SIGABRT: abort
> PC=0x8d02256 m=0 sigcode=0
> signal arrived during cgo execution
> 
> goroutine 1 [syscall, locked to thread]:
> runtime.cgocall(0x4ecbe70, 0xc0005afdb8, 0x469c613)
> 	GOROOT/src/runtime/cgocall.go:133 +0x5b fp=0xc0005afd88 sp=0xc0005afd50 pc=0x400527b
> github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsInit(0xf600000005, 0xc000000000)
> 	_cgo_gotypes.go:469 +0x4d fp=0xc0005afdb8 sp=0xc0005afd88 pc=0x472db2d
> github.com/herumi/bls-eth-go-binary/bls.Init(0x5, 0x0, 0x0)
> 	bls.go:43 +0x40 fp=0xc0005afe10 sp=0xc0005afdb8 pc=0x472ff30
> github.com/prysmaticlabs/prysm/shared/bls.init.0()
> 	shared/bls/bls.go:19 +0x2a fp=0xc0005afe38 sp=0xc0005afe10 pc=0x473510a
> runtime.doInit(0x61cfb40)
> 	GOROOT/src/runtime/proc.go:5414 +0x8a fp=0xc0005afe68 sp=0xc0005afe38 pc=0x404574a
> runtime.doInit(0x61d5c40)
> 	GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc0005afe98 sp=0xc0005afe68 pc=0x4045717
> runtime.doInit(0x61d12c0)
> 	GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc0005afec8 sp=0xc0005afe98 pc=0x4045717
> runtime.doInit(0x61e0bc0)
> 	GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc0005afef8 sp=0xc0005afec8 pc=0x4045717
> runtime.doInit(0x61d2b80)
> 	GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc0005aff28 sp=0xc0005afef8 pc=0x4045717
> runtime.doInit(0x61e0d60)
> 	GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc0005aff58 sp=0xc0005aff28 pc=0x4045717
> runtime.doInit(0x61d99a0)
> 	GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc0005aff88 sp=0xc0005aff58 pc=0x4045717
> runtime.main()
> 	GOROOT/src/runtime/proc.go:190 +0x1ce fp=0xc0005affe0 sp=0xc0005aff88 pc=0x4038b2e
> runtime.goexit()
> 	src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0005affe8 sp=0xc0005affe0 pc=0x4069471
> 
> goroutine 19 [select]:
> github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc00011c7e0)
> 	external/com_github_ipfs_go_log/writer/writer.go:76 +0x128
> created by github.com/ipfs/go-log/writer.NewMirrorWriter
> 	external/com_github_ipfs_go_log/writer/writer.go:41 +0xb9
> 
> goroutine 20 [select]:
> github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001a5740)
> 	external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
> created by github.com/dgraph-io/ristretto.newDefaultPolicy
> 	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129
> 
> goroutine 21 [select]:
> github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000134c00)
> 	external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
> created by github.com/dgraph-io/ristretto.NewCache
> 	external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3
> 
> goroutine 22 [select]:
> github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000252810)
> 	external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
> created by github.com/dgraph-io/ristretto.newDefaultPolicy
> 	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129
> 
> goroutine 23 [select]:
> github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000134d20)
> 	external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
> created by github.com/dgraph-io/ristretto.NewCache
> 	external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3
> 
> goroutine 24 [select]:
> github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0002778c0)
> 	external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
> created by github.com/dgraph-io/ristretto.newDefaultPolicy
> 	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129
> 
> goroutine 25 [select]:
> github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000134e40)
> 	external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
> created by github.com/dgraph-io/ristretto.NewCache
> 	external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3
> 
> goroutine 26 [select]:
> github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00027cae0)
> 	external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
> created by github.com/dgraph-io/ristretto.newDefaultPolicy
> 	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129
> 
> goroutine 27 [select]:
> github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000134f60)
> 	external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
> created by github.com/dgraph-io/ristretto.NewCache
> 	external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3
> 
> goroutine 34 [select]:
> github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0000d01b0)
> 	external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
> created by github.com/dgraph-io/ristretto.newDefaultPolicy
> 	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129
> 
> goroutine 35 [select]:
> github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0000965a0)
> 	external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
> created by github.com/dgraph-io/ristretto.NewCache
> 	external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3
> 
> rax    0x2000209
> rbx    0x4
> rcx    0x7ffeefbfe0b8
> rdx    0x7ffeefbfe530
> rdi    0x6
> rsi    0x4
> rbp    0x7ffeefbfe110
> rsp    0x7ffeefbfe0b8
> r8     0x7ffeefbfe130
> r9     0x0
> r10    0x7a
> r11    0x246
> r12    0x7a
> r13    0x7ffeefbfe530
> r14    0x6
> r15    0x0
> rip    0x8d02256
> rflags 0x246
> cs     0x7
> fs     0x0
> gs     0x0
>

**Comment by prestonvanloon** [comment]
OS X 10.13.6 is not supported. Please use docker or upgrade to OS X 10.14 or greater.
