### PR TITLE
fix: reject out-of-range attestation committee index

### PR DESCRIPTION
**Pull request by phrwlk**
- Fix off-by-one in validateCommitteeIndexAndCount by rejecting committee_index >= committees_per_slot instead of only >.
- Previously allowed committee_index == committees_per_slot, which is out of range ([0, committees_per_slot - 1]) per spec and inconsistent with core processing.
- Aligns with existing checks in beacon-chain/core/blocks/attestation.go (Phase0 path uses >=) and comments in aggregated flow validating index < get_committee_count_per_slot(...).
- Prevents accepting invalid gossip that would be rejected later in the pipeline, ensuring consistent behavior across validation paths.

### CODE REVIEW

**Review by james-prysm — DISMISSED** [review]
Thanks for catching will double check with team but I think this is correct

**Comment by james-prysm** [comment]
Could you add a unit test?

**Comment by phrwlk** [comment]
> Could you add a unit test?

yes ser

**Comment by phrwlk** [comment]
> Could you add a unit test?

Done, ser

**Review by potuz — COMMENTED** [review]
Nice catch! this is a pre-genesis bug. Introduced in https://github.com/OffchainLabs/prysm/pull/7278

Could you please add a regression test?

**Review by potuz — DISMISSED** [review]
Oh the test was added as I reviewed this :) Nice one, thanks so much

**Comment by james-prysm** [comment]
looks like linting broke @phrwlk 

nogo: nogo: error running analyzers: 145 analyzers skipped due to type-checking error: beacon-chain/sync/validate_beacon_attestation_test.go:641:28: cannot use count - 1 (value of type uint64) as primitives.CommitteeIndex value in assignment

  Error: beacon-chain/sync/validate_beacon_attestation_test.go:641:28: cannot use count - 1 (value of type uint64) as primitives.CommitteeIndex value in assignment
  Error: beacon-chain/sync/validate_beacon_attestation_test.go:647:28: cannot use count (variable of type uint64) as primitives.CommitteeIndex value in assignment
  Error: beacon-chain/sync/validate_beacon_attestation_test.go:649:10: undefined: require.Error (typecheck)

**Comment by phrwlk** [comment]
> looks like linting broke @phrwlk
> 
> nogo: nogo: error running analyzers: 145 analyzers skipped due to type-checking error: beacon-chain/sync/validate_beacon_attestation_test.go:641:28: cannot use count - 1 (value of type uint64) as primitives.CommitteeIndex value in assignment
> 
> Error: beacon-chain/sync/validate_beacon_attestation_test.go:641:28: cannot use count - 1 (value of type uint64) as primitives.CommitteeIndex value in assignment Error: beacon-chain/sync/validate_beacon_attestation_test.go:647:28: cannot use count (variable of type uint64) as primitives.CommitteeIndex value in assignment Error: beacon-chain/sync/validate_beacon_attestation_test.go:649:10: undefined: require.Error (typecheck)

I think now it must be ok, tests passed locally

**Comment by james-prysm** [comment]
@phrwlk unit test is still broken 😓

**Comment by james-prysm** [comment]
I fixed and pushed the test

**Review by Inspector-Butters — APPROVED** [review]

**Comment by phrwlk** [comment]
> I fixed and pushed the test

i'm sorry for the delay
